// GENERATED FILE -- DO NOT EDIT.
//
// Emitted by `webgen/web_taxonomy_export.py` from `webgen/taxonomy.json` (types, labels and
// `mechanical_fields`) and `webgen/mechanic_labels.json` (the hand-authored Spanish labels for
// mechanics KEYS). Re-emitted by `cd webgen && ../pipeline/.venv/bin/python regen.py` and
// byte-diffed against a fresh regeneration by `webgen/tests/test_derivation_drift.py`, so a hand
// edit here is a guard failure, not a change.
//
// This file replaces the hand-kept copy that used to live in `taxonomy.ts`. That copy disagreed
// with the canonical registry on 41 of the 57 types it declared and omitted 7 more, and nothing
// compared them -- a diff-based check cannot run in the submodule-free CI job, so the mirror was
// made DERIVED instead. Presentation logic (the fallback formatters, line and sphere labels) stays
// hand-written in `taxonomy.ts`, which re-exports what this file declares.
//
// `mechanical_fields` sets the field ORDER `StatBlock.astro` renders; it never restricts what is
// rendered (undeclared keys are appended). `MECHANIC_LABELS` is incomplete BY VERDICT: nothing in
// the corpus states a Spanish label for a mechanics key, so unlabelled keys fall back to a
// readable formatting of the raw key rather than to an invented translation.

export interface TypeInfo {
  /** Spanish label for the entity type (singular). */
  label_es: string;
  /** Mechanical fields this type carries, in declared display order. */
  mechanical_fields: string[];
}

export const TYPE_INFO: Record<string, TypeInfo> = {
  affiliation: { label_es: 'Afiliación', mechanical_fields: ['category', 'affinity_sphere', 'note'] },
  arcanos: { label_es: 'Arcanos', mechanical_fields: [] },
  'arcanos-power': { label_es: 'Poder de Arcanos', mechanical_fields: ['level', 'arcanos'] },
  archetype: { label_es: 'Arquetipo', mechanical_fields: ['regain_condition'] },
  armor: { label_es: 'Armadura', mechanical_fields: ['rating', 'penalty', 'is_shield', 'shield_bonus'] },
  art: { label_es: 'Arte', mechanical_fields: ['dice_pool', 'base_difficulty'] },
  artifact: { label_es: 'Artefacto', mechanical_fields: ['level'] },
  background: { label_es: 'Trasfondo', mechanical_fields: ['rating_max', 'ratings'] },
  bane: { label_es: 'Perdición', mechanical_fields: ['rage', 'gnosis', 'willpower', 'essence', 'charms'] },
  cantrip: { label_es: 'Ensalmo', mechanical_fields: ['art', 'level', 'type', 'successes'] },
  'changing-breed': { label_es: 'Raza Cambiante', mechanical_fields: [] },
  'chantry-trait': { label_es: 'Rasgo de Capilla/Constructo', mechanical_fields: ['pool_cost_per_dot', 'cap_rule', 'tier_bands', 'flavor_names', 'ratings'] },
  charm: { label_es: 'Encantamiento de Espíritu', mechanical_fields: ['essence_cost', 'freebie_cost', 'level', 'pcBuyable', 'cost_note'] },
  clan: { label_es: 'Clan', mechanical_fields: ['disciplines', 'weakness'] },
  'combination-discipline': { label_es: 'Disciplina Combinada', mechanical_fields: ['disciplines', 'cost', 'experience_cost', 'prerequisites', 'roll'] },
  conviction: { label_es: 'Convicción', mechanical_fields: [] },
  'dark-arcanos': { label_es: 'Arcano Oscuro', mechanical_fields: ['arcanos', 'arcanos_en', 'level', 'rank', 'cost', 'roll', 'dark_kingdom', 'difficulty'] },
  derangement: { label_es: 'Trastorno', mechanical_fields: ['category'] },
  discipline: { label_es: 'Disciplina', mechanical_fields: [] },
  'discipline-power': { label_es: 'Poder de Disciplina', mechanical_fields: ['discipline', 'level'] },
  'discipline-ritual': { label_es: 'Ritual de Disciplina', mechanical_fields: ['level', 'discipline_es', 'level_label_es', 'system_es', 'system_general', 'components'] },
  edge: { label_es: 'Filo', mechanical_fields: [] },
  equipment: { label_es: 'Equipo', mechanical_fields: ['category', 'effect'] },
  fetish: { label_es: 'Fetiche', mechanical_fields: ['gnosis', 'level'] },
  fetter: { label_es: 'Vínculo', mechanical_fields: ['note'] },
  flaw: { label_es: 'Defecto', mechanical_fields: ['bonus', 'category', 'prerequisites'] },
  fomor: { label_es: 'Fomor', mechanical_fields: ['willpower', 'powers'] },
  gift: { label_es: 'Don', mechanical_fields: ['rank', 'breed_auspice'] },
  guild: { label_es: 'Gremio', mechanical_fields: ['associated_arcanos', 'guild_marks'] },
  'hedge-path': { label_es: 'Senda de Hechicería', mechanical_fields: [] },
  house: { label_es: 'Casa', mechanical_fields: ['court_alignment', 'tier', 'nickname', 'boon', 'flaw', 'exile_story', 'pronunciation'] },
  instrument: { label_es: 'Instrumento', mechanical_fields: [] },
  kith: { label_es: 'Linaje', mechanical_fields: ['affinity_realm', 'birthrights', 'frailty', 'quote', 'appearance'] },
  legacy: { label_es: 'Legado', mechanical_fields: ['court_type', 'quest', 'ban'] },
  maneuver: { label_es: 'Maniobra', mechanical_fields: ['category', 'style', 'tier', 'applies_to', 'roll', 'difficulty', 'damage', 'min_ability', 'prerequisites', 'budget_class'] },
  'martial-art': { label_es: 'Arte Marcial', mechanical_fields: ['style_type', 'eight_limbs'] },
  merit: { label_es: 'Mérito', mechanical_fields: ['cost', 'category'] },
  'necromancy-path': { label_es: 'Senda de Nigromancia', mechanical_fields: ['discipline', 'path_note', 'levels'] },
  numen: { label_es: 'Numen', mechanical_fields: ['category', 'roll', 'difficulty', 'cost', 'duration'] },
  paradigm: { label_es: 'Paradigma', mechanical_fields: ['associated_practices'] },
  'path-of-enlightenment': { label_es: 'Senda de Iluminación', mechanical_fields: ['nickname', 'virtues', 'bearing', 'ethics', 'hierarchy_of_sins'] },
  practice: { label_es: 'Práctica', mechanical_fields: ['associated_abilities', 'associated_paradigms', 'common_instruments'] },
  'psychic-phenomenon': { label_es: 'Fenómeno Psíquico', mechanical_fields: ['ratings'] },
  realm: { label_es: 'Reino', mechanical_fields: ['levels'] },
  relic: { label_es: 'Reliquia', mechanical_fields: ['rating', 'item_type', 'effect'] },
  resonance: { label_es: 'Resonancia', mechanical_fields: ['flavor', 'descripciones'] },
  'revenant-family': { label_es: 'Familia Revenant', mechanical_fields: [] },
  rite: { label_es: 'Rito', mechanical_fields: ['level', 'roll', 'type_label', 'sistema_es', 'categoria'] },
  ritual: { label_es: 'Ritual', mechanical_fields: ['spheres', 'rank', 'path_es', 'path_en'] },
  rote: { label_es: 'Fórmula', mechanical_fields: ['spheres', 'effect', 'spelltype', 'spheres_note'] },
  'secondary-ability': { label_es: 'Habilidad secundaria', mechanical_fields: ['category', 'ratings'] },
  'secret-society': { label_es: 'Sociedad secreta', mechanical_fields: ['membership', 'rites', 'boon', 'ban', 'recruitment'] },
  'shadow-archetype': { label_es: 'Arquetipo de la Sombra', mechanical_fields: [] },
  'sorcery-ritual': { label_es: 'Ritual de Hechicería', mechanical_fields: [] },
  'special-advantage': { label_es: 'Ventaja Especial', mechanical_fields: ['cost', 'cost_note'] },
  'sphere-effect': { label_es: 'Efecto de Esfera', mechanical_fields: ['sphere', 'level', 'effect', 'spheres'] },
  tactic: { label_es: 'Táctica', mechanical_fields: [] },
  'thaumaturgy-path': { label_es: 'Senda de Taumaturgia', mechanical_fields: ['discipline', 'levels', 'path_note', 'escuela'] },
  thorn: { label_es: 'Espina', mechanical_fields: ['cost', 'effect'] },
  totem: { label_es: 'Tótem', mechanical_fields: ['individual_traits', 'pack_traits', 'ban', 'background_cost', 'categoria'] },
  treasure: { label_es: 'Tesoro', mechanical_fields: ['object_type', 'rating', 'poder'] },
  vehicle: { label_es: 'Vehículo', mechanical_fields: ['category', 'safe_speed', 'max_speed', 'maneuverability', 'crew', 'passengers', 'durability', 'structure', 'weapons'] },
  weapon: { label_es: 'Arma', mechanical_fields: ['weapon_class', 'damage', 'damage_type', 'difficulty', 'conceal', 'range', 'rate', 'clip', 'pathos_cost', 'notes'] },
  wonder: { label_es: 'Maravilla', mechanical_fields: ['subtype', 'rank', 'arete', 'quintessence', 'background_cost'] },
};

export const MECHANIC_LABELS: Record<string, string> = {
  activation: 'Activación',
  affinity_realm: 'Reino afín',
  affinity_sphere: 'Esfera afín',
  analogous_sphere: 'Esfera análoga',
  appearance: 'Apariencia',
  applies_to: 'Se aplica a',
  arcano: 'Arcano',
  arcanos: 'Arcanos',
  area: 'Área',
  arete: 'Arete',
  arete_min: 'Arete mínimo',
  armor_class: 'Clase de armadura',
  arte: 'Arte',
  arts: 'Artes',
  associated_abilities: 'Habilidades asociadas',
  associated_arcanos: 'Arcanos asociado',
  associated_paradigms: 'Paradigmas asociados',
  associated_practices: 'Prácticas asociadas',
  associated_skills: 'Habilidades asociadas',
  associated_thorn: 'Espina asociada',
  background_cost: 'Coste de trasfondo',
  ban: 'Prohibición',
  base_spheres: 'Esferas base',
  bearing: 'Porte',
  benefits: 'Beneficios',
  birthrights: 'Privilegios',
  body_es: 'Descripción',
  bono: 'Bono',
  bonus: 'Bono',
  boon: 'Favor',
  casting_time: 'Tiempo de lanzamiento',
  categoria: 'Categoría',
  category: 'Categoría',
  charms: 'Encantamientos',
  clan: 'Clan',
  clase: 'Clase',
  clip: 'Cargador',
  coincidence: 'Coincidente',
  coincidental: 'Coincidente',
  coincidental_note: 'Nota de coincidencia',
  common_instruments: 'Instrumentos comunes',
  conceal: 'Ocultación',
  convention: 'Convención',
  cost: 'Coste',
  cost_or_rating: 'Coste / Puntuación',
  coste: 'Coste',
  coste_de_trasfondo: 'Coste de trasfondo',
  coste_quintaesencia: 'Coste de quintaesencia',
  coste_trasfondo: 'Coste de trasfondo',
  court_alignment: 'Corte',
  court_type: 'Corte',
  crew: 'Tripulación',
  cross_reference: 'Referencia',
  damage: 'Daño',
  damage_type: 'Tipo de daño',
  dano: 'Daño',
  dark_passions: 'Pasiones oscuras',
  'daño': 'Daño',
  descripciones: 'Descripciones',
  dice_pool: 'Reserva de dados',
  difficulty: 'Dificultad',
  dificultad: 'Dificultad',
  dificultad_base: 'Dificultad base',
  discipline: 'Disciplina',
  durability: 'Durabilidad',
  duracion: 'Duración',
  duration: 'Duración',
  duration_note: 'Nota de duración',
  efecto: 'Efecto',
  efecto_esfera: 'Efecto de esfera',
  effect: 'Efecto',
  effect_class: 'Clase de efecto',
  eight_limbs: 'Ocho miembros',
  ejemplo: 'Ejemplo',
  ejemplos: 'Ejemplos',
  energia_primordial: 'Energía primordial',
  esfera: 'Esfera',
  esferas: 'Esferas',
  esferas_afines: 'Esferas afines',
  essence: 'Esencia',
  ethics: 'Ética',
  examples: 'Ejemplos',
  exile_story: 'Exilio',
  exitos: 'Éxitos',
  external_reference: 'Referencia',
  faction: 'Facción',
  flavor: 'Matiz',
  flaw: 'Defecto',
  frailty: 'Flaqueza',
  game_effect: 'Efecto de juego',
  gnosis: 'Gnosis',
  guild_marks: 'Marcas de gremio',
  habilidades_asociadas: 'Habilidades asociadas',
  healing: 'Curación',
  heraldry: 'Heráldica',
  hierarchy_of_sins: 'Jerarquía de pecados',
  illumination: 'Iluminación',
  iluminacion: 'Iluminación',
  instrumento: 'Instrumento',
  instrumentos_asociados: 'Instrumentos asociados',
  instrumentos_comunes: 'Instrumentos comunes',
  instruments: 'Instrumentos',
  is_shield: 'Escudo',
  level: 'Nivel',
  levels: 'Niveles',
  maintenance: 'Mantenimiento',
  maneuverability: 'Maniobrabilidad',
  maneuvers: 'Maniobras',
  mantenimiento: 'Mantenimiento',
  material: 'Material',
  max_speed: 'Velocidad máxima',
  membership: 'Membresía',
  min_ability: 'Habilidad mínima',
  modificador: 'Modificador',
  modificador_dificultad: 'Modificador de dificultad',
  modifier: 'Modificador',
  nature: 'Naturaleza',
  nickname: 'Apodo',
  nota: 'Nota',
  nota_fuente: 'Nota de fuente',
  notas: 'Notas',
  note: 'Nota',
  notes: 'Notas',
  paradigmas_asociados: 'Paradigmas asociados',
  paradoja: 'Paradoja',
  paradox: 'Paradoja',
  passengers: 'Pasajeros',
  path_es: 'Senda',
  pathos_cost: 'Coste de Pathos',
  penalty: 'Penalización',
  powers: 'Poderes',
  practicas_asociadas: 'Prácticas asociadas',
  practice: 'Práctica',
  premises: 'Premisas',
  prerequisite: 'Requisito',
  prerequisites: 'Requisitos',
  primal_energy: 'Energía primordial',
  procedure: 'Procedimiento',
  procedure_note: 'Nota de procedimiento',
  pronunciation: 'Pronunciación',
  quest: 'Búsqueda',
  quintaesencia: 'Quintaesencia',
  quintessence: 'Quintaesencia',
  quintessence_cost: 'Coste de quintaesencia',
  quote: 'Cita',
  rage: 'Rabia',
  range: 'Alcance',
  rango: 'Rango',
  rank: 'Rango',
  rate: 'Cadencia',
  rating: 'Puntuación',
  rating_max: 'Puntuación máxima',
  ratings: 'Puntuaciones',
  recruitment: 'Reclutamiento',
  reference: 'Referencia',
  referencia: 'Referencia',
  regain_condition: 'Condición de recuperación',
  requirement: 'Requisito',
  requirements: 'Requisitos',
  requisito: 'Requisito',
  resistance: 'Resistencia',
  resistencia: 'Resistencia',
  resonance: 'Resonancia',
  resonancia: 'Resonancia',
  restriccion: 'Restricción',
  restriction: 'Restricción',
  rites: 'Rituales y ritos',
  role: 'Función',
  roll: 'Tirada',
  roll_time: 'Tiempo de tirada',
  rolls: 'Tiradas',
  safe_speed: 'Velocidad segura',
  shield_bonus: 'Bonificación de escudo',
  sistema: 'Sistema',
  speed: 'Velocidad',
  sphere: 'Esfera',
  sphere_alias: 'Alias de esfera',
  sphere_base: 'Esfera base',
  sphere_note: 'Nota de esfera',
  sphere_requirement: 'Requisito de esfera',
  spheres: 'Esferas',
  spheres_base: 'Esferas base',
  stat_block: 'Bloque de rasgos',
  stat_line: 'Bloque de rasgos',
  statblock: 'Bloque de rasgos',
  status: 'Estado',
  strength_min: 'Fuerza mínima',
  structure: 'Estructura',
  style: 'Estilo',
  style_type: 'Tipo de estilo',
  subtype: 'Subtipo',
  successes: 'Éxitos',
  successes_needed: 'Éxitos necesarios',
  system: 'Sistema',
  table: 'Tabla',
  teaches: 'Enseña',
  tecnicas_asociadas: 'Técnicas asociadas',
  tier: 'Rango',
  tier_maneuver: 'Nivel',
  tipo: 'Tipo',
  tipo_magia: 'Tipo de magia',
  tirada: 'Tirada',
  tiradas: 'Tiradas',
  trigger: 'Detonante',
  usual_instruments: 'Instrumentos habituales',
  vehicle: 'Vehículo',
  vehicles: 'Vehículos',
  velocidad: 'Velocidad',
  virtues: 'Virtudes',
  vulgar: 'Vulgar',
  vulgar_coincident: 'Vulgar/Coincidente',
  vulgaridad: 'Vulgaridad',
  weapon_class: 'Clase de arma',
  weapons: 'Armas',
  willpower: 'Fuerza de Voluntad',
  wonder_subtype: 'Subtipo de maravilla',
  wonder_type: 'Tipo de maravilla',
};
